# Generated by Django 4.2 on 2023-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="carowner_django",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={"db_table": "carowner_django",},
        ),
    ]
