# Generated by Django 4.2 on 2023-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carownerapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="car_owner",
            fields=[
                (
                    "Number_plate",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("Phone_number", models.IntegerField()),
                ("ID", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="carowner_django",),
    ]
