# Generated by Django 4.2 on 2023-05-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carownerapp", "0002_car_owner_delete_carowner_django"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("Charges", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="County",
            fields=[
                ("county_code", models.IntegerField(primary_key=True, serialize=False)),
                ("county_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Identification",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Phone_Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Phone_Numbers", models.IntegerField(max_length=13)),
                (
                    "ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carownerapp.identification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Police_station",
            fields=[
                (
                    "Police_station_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("station_name", models.CharField(max_length=50)),
                ("sub_county", models.CharField(max_length=30)),
                ("ward", models.CharField(max_length=30)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carownerapp.county",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "Number_Plate",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_Updated", models.DateTimeField(auto_now=True)),
                (
                    "ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carownerapp.identification",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="car_owner",),
        migrations.AddField(
            model_name="charges",
            name="Number_Plate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="carownerapp.registration",
            ),
        ),
        migrations.AddField(
            model_name="charges",
            name="Police_station_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="carownerapp.police_station",
            ),
        ),
    ]
