# Generated by Django 4.2 on 2023-05-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carownerapp", "0003_charges_county_identification_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration", old_name="date_Updated", new_name="date",
        ),
        migrations.RemoveField(model_name="registration", name="date_created",),
    ]
