# Generated by Django 4.2 on 2023-05-26 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("carownerapp", "0004_rename_date_updated_registration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
