# Generated by Django 4.2 on 2023-05-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carownerapp", "0005_alter_registration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="police_station",
            name="Phone_Number",
            field=models.IntegerField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="police_station",
            name="sub_county",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="police_station",
            name="ward",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
