# Generated by Django 4.2 on 2023-05-29 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("carownerapp", "0006_police_station_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charges",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
