# Generated by Django 4.2 on 2023-05-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carownerapp', '0009_alter_charges_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_number',
            name='Phone_Numbers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='police_station',
            name='Phone_Number',
            field=models.IntegerField(null=True),
        ),
    ]
